table iris
	lineageTag: 00000000-0000-0000-0000-000000000001

	column 'Sepal.Length'
		dataType: double
		lineageTag: 00000000-0000-0000-0000-000000000002
		summarizeBy: sum
		sourceColumn: Sepal.Length

	column 'Sepal.Width'
		dataType: double
		lineageTag: 00000000-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: Sepal.Width

	column 'Petal.Length'
		dataType: double
		lineageTag: 00000000-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: Petal.Length

	column 'Petal.Width'
		dataType: double
		lineageTag: 00000000-0000-0000-0000-000000000005
		summarizeBy: sum
		sourceColumn: Petal.Width

	column Variety
		dataType: string
		lineageTag: 00000000-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Variety

	column 'iris.csv'
		dataType: string
		lineageTag: 00000000-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: iris.csv

	partition iris = m
		mode: import
		source =
			let
				SourceBinary = Binary.FromText("U2VwYWwuTGVuZ3RoLFNlcGFsLldpZHRoLFBldGFsLkxlbmd0aCxQZXRhbC5XaWR0aCxWYXJpZXR5CjUuMSwzLjUsMS40LDAuMixTZXRvc2EKNC45LDMuMCwxLjQsMC4yLFNldG9zYQo0LjcsMy4yLDEuMywwLjIsU2V0b3NhCjQuNiwzLjEsMS41LDAuMixTZXRvc2EKNS4wLDMuNiwxLjQsMC4yLFNldG9zYQo1LjQsMy45LDEuNywwLjQsU2V0b3NhCjQuNiwzLjQsMS40LDAuMyxTZXRvc2EKNS4wLDMuNCwxLjUsMC4yLFNldG9zYQo0LjQsMi45LDEuNCwwLjIsU2V0b3NhCjQuOSwzLjEsMS41LDAuMSxTZXRvc2EKNS40LDMuNywxLjUsMC4yLFNldG9zYQo0LjgsMy40LDEuNiwwLjIsU2V0b3NhCjQuOCwzLjAsMS40LDAuMSxTZXRvc2EKNC4zLDMuMCwxLjEsMC4xLFNldG9zYQo1LjgsNC4wLDEuMiwwLjIsU2V0b3NhCjUuNyw0LjQsMS41LDAuNCxTZXRvc2EKNS40LDMuOSwxLjMsMC40LFNldG9zYQo1LjEsMy41LDEuNCwwLjMsU2V0b3NhCjUuNywzLjgsMS43LDAuMyxTZXRvc2EKNS4xLDMuOCwxLjUsMC4zLFNldG9zYQo1LjQsMy40LDEuNywwLjIsU2V0b3NhCjUuMSwzLjcsMS41LDAuNCxTZXRvc2EKNC42LDMuNiwxLjAsMC4yLFNldG9zYQo1LjEsMy4zLDEuNywwLjUsU2V0b3NhCjQuOCwzLjQsMS45LDAuMixTZXRvc2EKNS4wLDMuMCwxLjYsMC4yLFNldG9zYQo1LjAsMy40LDEuNiwwLjQsU2V0b3NhCjUuMiwzLjUsMS41LDAuMixTZXRvc2EKNS4yLDMuNCwxLjQsMC4yLFNldG9zYQo0LjcsMy4yLDEuNiwwLjIsU2V0b3NhCjQuOCwzLjEsMS42LDAuMixTZXRvc2EKNS40LDMuNCwxLjUsMC40LFNldG9zYQo1LjIsNC4xLDEuNSwwLjEsU2V0b3NhCjUuNSw0LjIsMS40LDAuMixTZXRvc2EKNC45LDMuMSwxLjUsMC4yLFNldG9zYQo1LjAsMy4yLDEuMiwwLjIsU2V0b3NhCjUuNSwzLjUsMS4zLDAuMixTZXRvc2EKNC45LDMuNiwxLjQsMC4xLFNldG9zYQo0LjQsMy4wLDEuMywwLjIsU2V0b3NhCjUuMSwzLjQsMS41LDAuMixTZXRvc2EKNS4wLDMuNSwxLjMsMC4zLFNldG9zYQo0LjUsMi4zLDEuMywwLjMsU2V0b3NhCjQuNCwzLjIsMS4zLDAuMixTZXRvc2EKNS4wLDMuNSwxLjYsMC42LFNldG9zYQo1LjEsMy44LDEuOSwwLjQsU2V0b3NhCjQuOCwzLjAsMS40LDAuMyxTZXRvc2EKNS4xLDMuOCwxLjYsMC4yLFNldG9zYQo0LjYsMy4yLDEuNCwwLjIsU2V0b3NhCjUuMywzLjcsMS41LDAuMixTZXRvc2EKNS4wLDMuMywxLjQsMC4yLFNldG9zYQo3LjAsMy4yLDQuNywxLjQsVmVyc2ljb2xvcgo2LjQsMy4yLDQuNSwxLjUsVmVyc2ljb2xvcgo2LjksMy4xLDQuOSwxLjUsVmVyc2ljb2xvcgo1LjUsMi4zLDQuMCwxLjMsVmVyc2ljb2xvcgo2LjUsMi44LDQuNiwxLjUsVmVyc2ljb2xvcgo1LjcsMi44LDQuNSwxLjMsVmVyc2ljb2xvcgo2LjMsMy4zLDQuNywxLjYsVmVyc2ljb2xvcgo0LjksMi40LDMuMywxLjAsVmVyc2ljb2xvcgo2LjYsMi45LDQuNiwxLjMsVmVyc2ljb2xvcgo1LjIsMi43LDMuOSwxLjQsVmVyc2ljb2xvcgo1LjAsMi4wLDMuNSwxLjAsVmVyc2ljb2xvcgo1LjksMy4wLDQuMiwxLjUsVmVyc2ljb2xvcgo2LjAsMi4yLDQuMCwxLjAsVmVyc2ljb2xvcgo2LjEsMi45LDQuNywxLjQsVmVyc2ljb2xvcgo1LjYsMi45LDMuNiwxLjMsVmVyc2ljb2xvcgo2LjcsMy4xLDQuNCwxLjQsVmVyc2ljb2xvcgo1LjYsMy4wLDQuNSwxLjUsVmVyc2ljb2xvcgo1LjgsMi43LDQuMSwxLjAsVmVyc2ljb2xvcgo2LjIsMi4yLDQuNSwxLjUsVmVyc2ljb2xvcgo1LjYsMi41LDMuOSwxLjEsVmVyc2ljb2xvcgo1LjksMy4yLDQuOCwxLjgsVmVyc2ljb2xvcgo2LjEsMi44LDQuMCwxLjMsVmVyc2ljb2xvcgo2LjMsMi41LDQuOSwxLjUsVmVyc2ljb2xvcgo2LjEsMi44LDQuNywxLjIsVmVyc2ljb2xvcgo2LjQsMi45LDQuMywxLjMsVmVyc2ljb2xvcgo2LjYsMy4wLDQuNCwxLjQsVmVyc2ljb2xvcgo2LjgsMi44LDQuOCwxLjQsVmVyc2ljb2xvcgo2LjcsMy4wLDUuMCwxLjcsVmVyc2ljb2xvcgo2LjAsMi45LDQuNSwxLjUsVmVyc2ljb2xvcgo1LjcsMi42LDMuNSwxLjAsVmVyc2ljb2xvcgo1LjUsMi40LDMuOCwxLjEsVmVyc2ljb2xvcgo1LjUsMi40LDMuNywxLjAsVmVyc2ljb2xvcgo1LjgsMi43LDMuOSwxLjIsVmVyc2ljb2xvcgo2LjAsMi43LDUuMSwxLjYsVmVyc2ljb2xvcgo1LjQsMy4wLDQuNSwxLjUsVmVyc2ljb2xvcgo2LjAsMy40LDQuNSwxLjYsVmVyc2ljb2xvcgo2LjcsMy4xLDQuNywxLjUsVmVyc2ljb2xvcgo2LjMsMi4zLDQuNCwxLjMsVmVyc2ljb2xvcgo1LjYsMy4wLDQuMSwxLjMsVmVyc2ljb2xvcgo1LjUsMi41LDQuMCwxLjMsVmVyc2ljb2xvcgo1LjUsMi42LDQuNCwxLjIsVmVyc2ljb2xvcgo2LjEsMy4wLDQuNiwxLjQsVmVyc2ljb2xvcgo1LjgsMi42LDQuMCwxLjIsVmVyc2ljb2xvcgo1LjAsMi4zLDMuMywxLjAsVmVyc2ljb2xvcgo1LjYsMi43LDQuMiwxLjMsVmVyc2ljb2xvcgo1LjcsMy4wLDQuMiwxLjIsVmVyc2ljb2xvcgo1LjcsMi45LDQuMiwxLjMsVmVyc2ljb2xvcgo2LjIsMi45LDQuMywxLjMsVmVyc2ljb2xvcgo1LjEsMi41LDMuMCwxLjEsVmVyc2ljb2xvcgo1LjcsMi44LDQuMSwxLjMsVmVyc2ljb2xvcgo2LjMsMy4zLDYuMCwyLjUsVmlyZ2luaWNhCjUuOCwyLjcsNS4xLDEuOSxWaXJnaW5pY2EKNy4xLDMuMCw1LjksMi4xLFZpcmdpbmljYQo2LjMsMi45LDUuNiwxLjgsVmlyZ2luaWNhCjYuNSwzLjAsNS44LDIuMixWaXJnaW5pY2EKNy42LDMuMCw2LjYsMi4xLFZpcmdpbmljYQo0LjksMi41LDQuNSwxLjcsVmlyZ2luaWNhCjcuMywyLjksNi4zLDEuOCxWaXJnaW5pY2EKNi43LDIuNSw1LjgsMS44LFZpcmdpbmljYQo3LjIsMy42LDYuMSwyLjUsVmlyZ2luaWNhCjYuNSwzLjIsNS4xLDIuMCxWaXJnaW5pY2EKNi40LDIuNyw1LjMsMS45LFZpcmdpbmljYQo2LjgsMy4wLDUuNSwyLjEsVmlyZ2luaWNhCjUuNywyLjUsNS4wLDIuMCxWaXJnaW5pY2EKNS44LDIuOCw1LjEsMi40LFZpcmdpbmljYQo2LjQsMy4yLDUuMywyLjMsVmlyZ2luaWNhCjYuNSwzLjAsNS41LDEuOCxWaXJnaW5pY2EKNy43LDMuOCw2LjcsMi4yLFZpcmdpbmljYQo3LjcsMi42LDYuOSwyLjMsVmlyZ2luaWNhCjYuMCwyLjIsNS4wLDEuNSxWaXJnaW5pY2EKNi45LDMuMiw1LjcsMi4zLFZpcmdpbmljYQo1LjYsMi44LDQuOSwyLjAsVmlyZ2luaWNhCjcuNywyLjgsNi43LDIuMCxWaXJnaW5pY2EKNi4zLDIuNyw0LjksMS44LFZpcmdpbmljYQo2LjcsMy4zLDUuNywyLjEsVmlyZ2luaWNhCjcuMiwzLjIsNi4wLDEuOCxWaXJnaW5pY2EKNi4yLDIuOCw0LjgsMS44LFZpcmdpbmljYQo2LjEsMy4wLDQuOSwxLjgsVmlyZ2luaWNhCjYuNCwyLjgsNS42LDIuMSxWaXJnaW5pY2EKNy4yLDMuMCw1LjgsMS42LFZpcmdpbmljYQo3LjQsMi44LDYuMSwxLjksVmlyZ2luaWNhCjcuOSwzLjgsNi40LDIuMCxWaXJnaW5pY2EKNi40LDIuOCw1LjYsMi4yLFZpcmdpbmljYQo2LjMsMi44LDUuMSwxLjUsVmlyZ2luaWNhCjYuMSwyLjYsNS42LDEuNCxWaXJnaW5pY2EKNy43LDMuMCw2LjEsMi4zLFZpcmdpbmljYQo2LjMsMy40LDUuNiwyLjQsVmlyZ2luaWNhCjYuNCwzLjEsNS41LDEuOCxWaXJnaW5pY2EKNi4wLDMuMCw0LjgsMS44LFZpcmdpbmljYQo2LjksMy4xLDUuNCwyLjEsVmlyZ2luaWNhCjYuNywzLjEsNS42LDIuNCxWaXJnaW5pY2EKNi45LDMuMSw1LjEsMi4zLFZpcmdpbmljYQo1LjgsMi43LDUuMSwxLjksVmlyZ2luaWNhCjYuOCwzLjIsNS45LDIuMyxWaXJnaW5pY2EKNi43LDMuMyw1LjcsMi41LFZpcmdpbmljYQo2LjcsMy4wLDUuMiwyLjMsVmlyZ2luaWNhCjYuMywyLjUsNS4wLDEuOSxWaXJnaW5pY2EKNi41LDMuMCw1LjIsMi4wLFZpcmdpbmljYQo2LjIsMy40LDUuNCwyLjMsVmlyZ2luaWNhCjUuOSwzLjAsNS4xLDEuOCxWaXJnaW5pY2EK", BinaryEncoding.Base64),
				Source = Csv.Document(SourceBinary, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Promoted, {{"Sepal.Length", type number}, {"Sepal.Width", type number}, {"Petal.Length", type number}, {"Petal.Width", type number}, {"Variety", type text}, {"iris.csv", type text}})
			in
				Typed
